
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 01 10:36:56 EST 2019
//----------------------------------------------------

import java.io.*;

/** CUP v0.10k generated parser.
  * @version Fri Mar 01 10:36:56 EST 2019
  */
public class A3Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public A3Parser() {super();}

  /** Constructor which sets the default scanner. */
  public A3Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\003\004\000\002\002\004\000\002\003" +
    "\002\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\012\011\000\002\012\010\000\002\013\004\000" +
    "\002\013\002\000\002\010\005\000\002\010\002\000\002" +
    "\014\004\000\002\015\005\000\002\004\004\000\002\004" +
    "\003\000\002\016\003\000\002\016\003\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003\000\002\017\005\000\002\017\004\000\002" +
    "\020\006\000\002\020\006\000\002\021\005\000\002\022" +
    "\007\000\002\022\011\000\002\023\011\000\002\024\011" +
    "\000\002\025\004\000\002\007\005\000\002\007\005\000" +
    "\002\007\002\000\002\026\004\000\002\006\005\000\002" +
    "\006\005\000\002\006\002\000\002\027\003\000\002\027" +
    "\003\000\002\027\005\000\002\027\006\000\002\030\005" +
    "\000\002\030\005\000\002\031\004\000\002\031\002\000" +
    "\002\005\005\000\002\005\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\012\002\uffff\020\007\021\005\022\011\001" +
    "\002\000\004\002\155\001\002\000\006\023\ufffd\027\ufffd" +
    "\001\002\000\012\002\uffff\020\007\021\005\022\011\001" +
    "\002\000\006\023\ufffe\027\ufffe\001\002\000\006\023\013" +
    "\027\012\001\002\000\006\023\ufffc\027\ufffc\001\002\000" +
    "\004\023\147\001\002\000\004\007\014\001\002\000\012" +
    "\010\ufff8\020\007\021\005\022\011\001\002\000\006\006" +
    "\144\010\ufff6\001\002\000\004\010\021\001\002\000\004" +
    "\023\020\001\002\000\006\006\ufff5\010\ufff5\001\002\000" +
    "\004\025\022\001\002\000\024\020\007\021\005\022\011" +
    "\023\025\025\022\030\026\031\030\033\031\034\032\001" +
    "\002\000\012\002\ufffa\020\ufffa\021\ufffa\022\ufffa\001\002" +
    "\000\004\023\141\001\002\000\004\015\133\001\002\000" +
    "\010\007\044\023\045\024\046\001\002\000\026\020\007" +
    "\021\005\022\011\023\025\025\022\026\127\030\026\031" +
    "\030\033\031\034\032\001\002\000\004\007\114\001\002" +
    "\000\004\007\106\001\002\000\004\007\043\001\002\000" +
    "\030\020\uffeb\021\uffeb\022\uffeb\023\uffeb\025\uffeb\026\uffeb" +
    "\030\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\001\002\000" +
    "\030\020\uffec\021\uffec\022\uffec\023\uffec\025\uffec\026\uffec" +
    "\030\uffec\031\uffec\032\uffec\033\uffec\034\uffec\001\002\000" +
    "\030\020\uffed\021\uffed\022\uffed\023\uffed\025\uffed\026\uffed" +
    "\030\uffed\031\uffed\032\uffed\033\uffed\034\uffed\001\002\000" +
    "\030\020\uffee\021\uffee\022\uffee\023\uffee\025\uffee\026\uffee" +
    "\030\uffee\031\uffee\032\uffee\033\uffee\034\uffee\001\002\000" +
    "\030\020\uffef\021\uffef\022\uffef\023\uffef\025\uffef\026\uffef" +
    "\030\uffef\031\uffef\032\uffef\033\uffef\034\uffef\001\002\000" +
    "\030\020\ufff0\021\ufff0\022\ufff0\023\ufff0\025\ufff0\026\ufff0" +
    "\030\ufff0\031\ufff0\032\ufff0\033\ufff0\034\ufff0\001\002\000" +
    "\026\020\ufff2\021\ufff2\022\ufff2\023\ufff2\025\ufff2\026\ufff2" +
    "\030\ufff2\031\ufff2\033\ufff2\034\ufff2\001\002\000\030\020" +
    "\ufff1\021\ufff1\022\ufff1\023\ufff1\025\ufff1\026\ufff1\030\ufff1" +
    "\031\ufff1\032\ufff1\033\ufff1\034\ufff1\001\002\000\010\007" +
    "\044\023\045\024\046\001\002\000\010\007\044\023\045" +
    "\024\046\001\002\000\026\005\uffd8\006\uffd8\007\074\010" +
    "\uffd8\011\uffd8\012\uffd8\013\uffd8\014\uffd8\016\uffd8\017\uffd8" +
    "\001\002\000\024\005\uffd9\006\uffd9\010\uffd9\011\uffd9\012" +
    "\uffd9\013\uffd9\014\uffd9\016\uffd9\017\uffd9\001\002\000\024" +
    "\005\uffda\006\uffda\010\uffda\011\uffda\012\uffda\013\065\014" +
    "\067\016\uffda\017\uffda\001\002\000\020\005\uffde\006\uffde" +
    "\010\uffde\011\056\012\057\016\uffde\017\uffde\001\002\000" +
    "\004\006\052\001\002\000\004\004\053\001\002\000\004" +
    "\010\054\001\002\000\004\005\055\001\002\000\030\020" +
    "\uffe3\021\uffe3\022\uffe3\023\uffe3\025\uffe3\026\uffe3\030\uffe3" +
    "\031\uffe3\032\uffe3\033\uffe3\034\uffe3\001\002\000\010\007" +
    "\044\023\045\024\046\001\002\000\010\007\044\023\045" +
    "\024\046\001\002\000\014\005\uffe1\006\uffe1\010\uffe1\016" +
    "\uffe1\017\uffe1\001\002\000\020\005\uffde\006\uffde\010\uffde" +
    "\011\056\012\057\016\uffde\017\uffde\001\002\000\014\005" +
    "\uffdf\006\uffdf\010\uffdf\016\uffdf\017\uffdf\001\002\000\020" +
    "\005\uffde\006\uffde\010\uffde\011\056\012\057\016\uffde\017" +
    "\uffde\001\002\000\014\005\uffe0\006\uffe0\010\uffe0\016\uffe0" +
    "\017\uffe0\001\002\000\010\007\044\023\045\024\046\001" +
    "\002\000\020\005\uffdd\006\uffdd\010\uffdd\011\uffdd\012\uffdd" +
    "\016\uffdd\017\uffdd\001\002\000\010\007\044\023\045\024" +
    "\046\001\002\000\024\005\uffda\006\uffda\010\uffda\011\uffda" +
    "\012\uffda\013\065\014\067\016\uffda\017\uffda\001\002\000" +
    "\020\005\uffdb\006\uffdb\010\uffdb\011\uffdb\012\uffdb\016\uffdb" +
    "\017\uffdb\001\002\000\024\005\uffda\006\uffda\010\uffda\011" +
    "\uffda\012\uffda\013\065\014\067\016\uffda\017\uffda\001\002" +
    "\000\020\005\uffdc\006\uffdc\010\uffdc\011\uffdc\012\uffdc\016" +
    "\uffdc\017\uffdc\001\002\000\012\007\044\010\uffd2\023\045" +
    "\024\046\001\002\000\004\010\103\001\002\000\006\006" +
    "\100\010\uffd0\001\002\000\004\010\uffd3\001\002\000\010" +
    "\007\044\023\045\024\046\001\002\000\006\006\100\010" +
    "\uffd0\001\002\000\004\010\uffd1\001\002\000\024\005\uffd6" +
    "\006\uffd6\010\uffd6\011\uffd6\012\uffd6\013\uffd6\014\uffd6\016" +
    "\uffd6\017\uffd6\001\002\000\004\010\105\001\002\000\024" +
    "\005\uffd7\006\uffd7\010\uffd7\011\uffd7\012\uffd7\013\uffd7\014" +
    "\uffd7\016\uffd7\017\uffd7\001\002\000\004\023\107\001\002" +
    "\000\004\006\110\001\002\000\004\004\111\001\002\000" +
    "\004\010\112\001\002\000\004\005\113\001\002\000\030" +
    "\020\uffe2\021\uffe2\022\uffe2\023\uffe2\025\uffe2\026\uffe2\030" +
    "\uffe2\031\uffe2\032\uffe2\033\uffe2\034\uffe2\001\002\000\010" +
    "\007\044\023\045\024\046\001\002\000\004\010\123\001" +
    "\002\000\006\016\120\017\117\001\002\000\010\007\044" +
    "\023\045\024\046\001\002\000\010\007\044\023\045\024" +
    "\046\001\002\000\004\010\uffd5\001\002\000\004\010\uffd4" +
    "\001\002\000\024\020\007\021\005\022\011\023\025\025" +
    "\022\030\026\031\030\033\031\034\032\001\002\000\030" +
    "\020\uffe5\021\uffe5\022\uffe5\023\uffe5\025\uffe5\026\uffe5\030" +
    "\uffe5\031\uffe5\032\125\033\uffe5\034\uffe5\001\002\000\024" +
    "\020\007\021\005\022\011\023\025\025\022\030\026\031" +
    "\030\033\031\034\032\001\002\000\030\020\uffe4\021\uffe4" +
    "\022\uffe4\023\uffe4\025\uffe4\026\uffe4\030\uffe4\031\uffe4\032" +
    "\uffe4\033\uffe4\034\uffe4\001\002\000\032\002\ufff4\020\ufff4" +
    "\021\ufff4\022\ufff4\023\ufff4\025\ufff4\026\ufff4\030\ufff4\031" +
    "\ufff4\032\ufff4\033\ufff4\034\ufff4\001\002\000\026\020\ufff3" +
    "\021\ufff3\022\ufff3\023\ufff3\025\ufff3\026\ufff3\030\ufff3\031" +
    "\ufff3\033\ufff3\034\ufff3\001\002\000\004\005\132\001\002" +
    "\000\030\020\uffe6\021\uffe6\022\uffe6\023\uffe6\025\uffe6\026" +
    "\uffe6\030\uffe6\031\uffe6\032\uffe6\033\uffe6\034\uffe6\001\002" +
    "\000\012\004\134\007\044\023\045\024\046\001\002\000" +
    "\004\005\137\001\002\000\004\005\136\001\002\000\030" +
    "\020\uffe8\021\uffe8\022\uffe8\023\uffe8\025\uffe8\026\uffe8\030" +
    "\uffe8\031\uffe8\032\uffe8\033\uffe8\034\uffe8\001\002\000\030" +
    "\020\uffe7\021\uffe7\022\uffe7\023\uffe7\025\uffe7\026\uffe7\030" +
    "\uffe7\031\uffe7\032\uffe7\033\uffe7\034\uffe7\001\002\000\030" +
    "\020\uffe9\021\uffe9\022\uffe9\023\uffe9\025\uffe9\026\uffe9\030" +
    "\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9\001\002\000\006" +
    "\005\142\015\133\001\002\000\030\020\uffea\021\uffea\022" +
    "\uffea\023\uffea\025\uffea\026\uffea\030\uffea\031\uffea\032\uffea" +
    "\033\uffea\034\uffea\001\002\000\004\010\ufff9\001\002\000" +
    "\010\020\007\021\005\022\011\001\002\000\006\006\144" +
    "\010\ufff6\001\002\000\004\010\ufff7\001\002\000\004\007" +
    "\150\001\002\000\012\010\ufff8\020\007\021\005\022\011" +
    "\001\002\000\004\010\152\001\002\000\004\025\022\001" +
    "\002\000\012\002\ufffb\020\ufffb\021\ufffb\022\ufffb\001\002" +
    "\000\004\002\001\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\010\003\003\011\007\012\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\153\011\007" +
    "\012\005\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\011\016\013\015\014\014\001\001\000\004\010\142\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\015\022\001\001\000\026\004\026\011\023\015" +
    "\041\016\040\017\037\020\036\021\035\022\034\023\033" +
    "\024\032\001\001\000\002\001\001\000\004\020\137\001" +
    "\001\000\002\001\001\000\010\025\130\026\047\027\046" +
    "\001\001\000\024\011\023\015\041\016\127\017\037\020" +
    "\036\021\035\022\034\023\033\024\032\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\025\050\026\047\027\046\001\001" +
    "\000\010\025\103\026\047\027\046\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\065\001\001\000\004" +
    "\007\057\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\026\062\027\046\001\001\000\006\026\060\027\046\001" +
    "\001\000\002\001\001\000\004\007\061\001\001\000\002" +
    "\001\001\000\004\007\063\001\001\000\002\001\001\000" +
    "\004\027\071\001\001\000\002\001\001\000\004\027\067" +
    "\001\001\000\004\006\070\001\001\000\002\001\001\000" +
    "\004\006\072\001\001\000\002\001\001\000\012\025\075" +
    "\026\047\027\046\031\074\001\001\000\002\001\001\000" +
    "\004\005\076\001\001\000\002\001\001\000\010\025\100" +
    "\026\047\027\046\001\001\000\004\005\101\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\025\115\026\047\027\046\030\114\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\121\026\047" +
    "\027\046\001\001\000\010\025\120\026\047\027\046\001" +
    "\001\000\002\001\001\000\002\001\001\000\024\011\023" +
    "\015\041\016\123\017\037\020\036\021\035\022\034\023" +
    "\033\024\032\001\001\000\002\001\001\000\024\011\023" +
    "\015\041\016\125\017\037\020\036\021\035\022\034\023" +
    "\033\024\032\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\025\134\026\047\027\046\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\016\014\144\001\001\000\004\010" +
    "\145\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\011\016\013\150\014\014\001\001\000\002\001\001\000" +
    "\004\015\152\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$A3Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$A3Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$A3Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$A3Parser$actions {

 int x = 0; 
  private final A3Parser parser;

  /** Constructor */
  CUP$A3Parser$actions(A3Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$A3Parser$do_action(
    int                        CUP$A3Parser$act_num,
    java_cup.runtime.lr_parser CUP$A3Parser$parser,
    java.util.Stack            CUP$A3Parser$stack,
    int                        CUP$A3Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$A3Parser$result;

      /* select the action based on the action number */
      switch (CUP$A3Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // _42 ::= 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(3/*_42*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // _42 ::= _16 _58 _42 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(3/*_42*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // _62 ::= 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(23/*_62*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // _62 ::= _58 _42 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(23/*_62*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // _61 ::= _58 _25 _58 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(22/*_61*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // _61 ::= _58 _24 _58 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(22/*_61*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // _60 ::= _14 _17 _62 _18 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(21/*_60*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // _60 ::= _17 _58 _18 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(21/*_60*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // _60 ::= _14 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(21/*_60*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // _60 ::= _13 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(21/*_60*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // _43 ::= 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(4/*_43*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // _43 ::= _22 _60 _43 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(4/*_43*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // _43 ::= _21 _60 _43 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(4/*_43*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // _59 ::= _60 _43 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(20/*_59*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // _44 ::= 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(5/*_44*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // _44 ::= _20 _59 _44 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(5/*_44*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // _44 ::= _19 _59 _44 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(5/*_44*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // _58 ::= _59 _44 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(19/*_58*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // _57 ::= _3 _17 _14 _16 _1 _18 _15 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(18/*_57*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // _56 ::= _2 _17 _58 _16 _1 _18 _15 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(17/*_56*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // _55 ::= _4 _17 _61 _18 _51 _5 _51 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(16/*_55*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // _55 ::= _4 _17 _61 _18 _51 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(16/*_55*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // _54 ::= _6 _58 _15 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(15/*_54*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // _53 ::= _14 _23 _1 _15 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(14/*_53*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // _53 ::= _14 _23 _58 _15 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(14/*_53*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // _52 ::= _46 _53 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(13/*_52*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // _52 ::= _46 _14 _15 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(13/*_52*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // _51 ::= _57 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // _51 ::= _56 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // _51 ::= _55 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // _51 ::= _54 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // _51 ::= _53 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // _51 ::= _52 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // _51 ::= _50 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(12/*_51*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // _41 ::= _51 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(2/*_41*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // _41 ::= _41 _51 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(2/*_41*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // _50 ::= _7 _41 _8 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(11/*_50*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // _49 ::= _46 _14 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(10/*_49*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // _45 ::= 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(6/*_45*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // _45 ::= _16 _49 _45 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(6/*_45*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // _48 ::= 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(9/*_48*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // _48 ::= _49 _45 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(9/*_48*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // _47 ::= _46 _14 _17 _48 _18 _50 
            {
              Object RESULT = null;
		 x++; 
              CUP$A3Parser$result = new java_cup.runtime.Symbol(8/*_47*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // _47 ::= _46 _9 _14 _17 _48 _18 _50 
            {
              Object RESULT = null;
		 x++; 
              CUP$A3Parser$result = new java_cup.runtime.Symbol(8/*_47*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // _46 ::= _10 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(7/*_46*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // _46 ::= _12 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(7/*_46*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // _46 ::= _11 
            {
              Object RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(7/*_46*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // __ ::= 
            {
              Integer RESULT = null;

              CUP$A3Parser$result = new java_cup.runtime.Symbol(1/*__*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= __ EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).right;
		Integer start_val = (Integer)((java_cup.runtime.Symbol) CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).value;
		RESULT = start_val;
              CUP$A3Parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$A3Parser$parser.done_parsing();
          return CUP$A3Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // __ ::= _47 __ 
            {
              Integer RESULT = null;
		 RESULT = x; 
              CUP$A3Parser$result = new java_cup.runtime.Symbol(1/*__*/, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$A3Parser$stack.elementAt(CUP$A3Parser$top-0)).right, RESULT);
            }
          return CUP$A3Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

