
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 01 10:36:56 EST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int _19 = 7;
  public static final int _18 = 6;
  public static final int _17 = 5;
  public static final int _16 = 4;
  public static final int _15 = 3;
  public static final int _9 = 21;
  public static final int _14 = 17;
  public static final int _8 = 20;
  public static final int _13 = 18;
  public static final int _7 = 19;
  public static final int _12 = 15;
  public static final int _6 = 22;
  public static final int _11 = 14;
  public static final int _5 = 24;
  public static final int _10 = 16;
  public static final int _4 = 23;
  public static final int _3 = 25;
  public static final int _2 = 26;
  public static final int _1 = 2;
  public static final int _25 = 13;
  public static final int _24 = 12;
  public static final int _23 = 11;
  public static final int _22 = 10;
  public static final int _21 = 9;
  public static final int _20 = 8;
  public static final int EOF = 0;
  public static final int error = 1;
}

